name: CI
on: push
permissions:
  contents: read
jobs:
  tests:
    strategy:
      matrix:
        version: ["1.17", "1.18", "1.19", "1.20"]
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ matrix.version }}

      - name: Run tests
        run: go test -coverpkg=./... -race -covermode=atomic ./...

  lint:
    name: Run Linter
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: "1.20"

      - name: Lint
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # 3.4.0
        with:
          version: "v1.51"
